// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPzp2hzcftx96zzetHF1APMaANL73FB6I',
    appId: '1:541713979906:web:5d0b4ca7847d4f39a5251b',
    messagingSenderId: '541713979906',
    projectId: 'diamondnib',
    authDomain: 'diamondnib.firebaseapp.com',
    storageBucket: 'diamondnib.firebasestorage.app',
    measurementId: 'G-RGPJ3WHV0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_auhKOOw6Aw6jzlW2IWfVjX7GE0UyoAM',
    appId: '1:541713979906:android:5d0b4ca7847d4f39a5251b',
    messagingSenderId: '541713979906',
    projectId: 'diamondnib',
    storageBucket: 'diamondnib.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDImkZVNgYlmxoe_Jl0_0jq7ky9r27EKy',
    appId: '1:541713979906:ios:5d0b4ca7847d4f39a5251b',
    messagingSenderId: '541713979906',
    projectId: 'diamondnib',
    storageBucket: 'diamondnib.appspot.com',
    iosClientId:
        '541713979906-psru8nso8theupot4cg7gdsrlbasgp0e.apps.googleusercontent.com',
    iosBundleId: 'com.diamondnib.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv8lz2mfppOZhU4AH9F2pWx3Os6IcoACg',
    appId: '1:541713979906:ios:5d0b4ca7847d4f39a5251b',
    messagingSenderId: '541713979906',
    projectId: 'diamondnib',
    storageBucket: 'diamondnib.appspot.com',
    iosClientId:
        '541713979906-psru8nso8theupot4cg7gdsrlbasgp0e.apps.googleusercontent.com',
    iosBundleId: 'com.diamondnib.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPzp2hzcftx96zzetHF1APMaANL73FB6I',
    appId: '1:541713979906:web:5d0b4ca7847d4f39a5251b',
    messagingSenderId: '541713979906',
    projectId: 'diamondnib',
    authDomain: 'diamondnib.firebaseapp.com',
    storageBucket: 'diamondnib.firebasestorage.app',
    measurementId: 'G-RGPJ3WHV0J',
  );
}
